customhost = "employee-db.crmzpcr8khk9.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "abc12345"
customdb = "employee"
custombucket = "melvinangwaihin-bucket"
customregion = "us-east-1"
